app_root: 'http://tools.pacificclimate.org/dataportal'
data_root: 'http://tools.pacificclimate.org/dataportal/data'
title: ''
ensemble_name: ''
dsn: postgresql://httpd@some.database.host/pcic_meta # add password for production
pcds_dsn: postgresql://httpd@some.database.host/crmp # add password for production
js_min: false
geoserver_url: http://tools.pacificclimate.org/geoserver/ # change for development
ncwms_url: 
    - http://tools.pacificclimate.org/ncWMS-PCIC/wms # change for development
tilecache_url: 
    - http://a.tiles.pacificclimate.org/tilecache/tilecache.py
    - http://b.tiles.pacificclimate.org/tilecache/tilecache.py
    - http://c.tiles.pacificclimate.org/tilecache/tilecache.py
session_dir: default
clean_session_dir: True # change for production
use_analytics: True
analytics: UA-20166041-3 # change for production
